// AUTO-GENERATED by scripts/gen-supabase-types.mjs — do not edit by hand.
// Source: external Supabase project PostgREST schema (https://quvqjctlskmqeyhognvd.supabase.co).
// Regenerate with: SERVICE_ROLE_KEY=... node scripts/gen-supabase-types.mjs

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type ExternalDatabase = {
  public: {
    Tables: {
      "admin_profiles": {
        Row: {
        "createdAt": string;
        "email": string;
        "id": string;
        "name": string;
        "role": string;
        };
        Insert: {
        "createdAt"?: string;
        "email": string;
        "id": string;
        "name": string;
        "role": string;
        };
        Update: {
        "createdAt"?: string;
        "email"?: string;
        "id"?: string;
        "name"?: string;
        "role"?: string;
        };
        Relationships: [];
      };
      "att_edit_requests": {
        Row: {
        "classSN": string;
        "createdAt": string;
        "email": string;
        "id": string;
        "name": string;
        "reason": string;
        "rejectionNote": string | null;
        "requestedStatus": string;
        "resolvedAt": string | null;
        "resolvedBy": string | null;
        "sessionId": string;
        "status": string;
        "workspace_id": string | null;
        };
        Insert: {
        "classSN": string;
        "createdAt"?: string;
        "email": string;
        "id": string;
        "name": string;
        "reason": string;
        "rejectionNote"?: string | null;
        "requestedStatus": string;
        "resolvedAt"?: string | null;
        "resolvedBy"?: string | null;
        "sessionId": string;
        "status"?: string;
        "workspace_id"?: string | null;
        };
        Update: {
        "classSN"?: string;
        "createdAt"?: string;
        "email"?: string;
        "id"?: string;
        "name"?: string;
        "reason"?: string;
        "rejectionNote"?: string | null;
        "requestedStatus"?: string;
        "resolvedAt"?: string | null;
        "resolvedBy"?: string | null;
        "sessionId"?: string;
        "status"?: string;
        "workspace_id"?: string | null;
        };
        Relationships: [];
      };
      "att_records": {
        Row: {
        "class": string;
        "classSN": string;
        "date": string;
        "email": string;
        "id": string;
        "name": string;
        "round": string | null;
        "sessionId": string;
        "status": string;
        "timestamp": string;
        "workspace_id": string | null;
        };
        Insert: {
        "class": string;
        "classSN": string;
        "date": string;
        "email": string;
        "id": string;
        "name": string;
        "round"?: string | null;
        "sessionId": string;
        "status": string;
        "timestamp"?: string;
        "workspace_id"?: string | null;
        };
        Update: {
        "class"?: string;
        "classSN"?: string;
        "date"?: string;
        "email"?: string;
        "id"?: string;
        "name"?: string;
        "round"?: string | null;
        "sessionId"?: string;
        "status"?: string;
        "timestamp"?: string;
        "workspace_id"?: string | null;
        };
        Relationships: [];
      };
      "att_sessions": {
        Row: {
        "class": string;
        "createdAt": string;
        "createdBy": string;
        "date": string;
        "id": string;
        "notes": string | null;
        "round1Serials": string[];
        "round2Serials": string[];
        "status": string;
        "topic": string;
        "workspace_id": string | null;
        };
        Insert: {
        "class": string;
        "createdAt"?: string;
        "createdBy": string;
        "date": string;
        "id": string;
        "notes"?: string | null;
        "round1Serials": string[];
        "round2Serials": string[];
        "status"?: string;
        "topic": string;
        "workspace_id"?: string | null;
        };
        Update: {
        "class"?: string;
        "createdAt"?: string;
        "createdBy"?: string;
        "date"?: string;
        "id"?: string;
        "notes"?: string | null;
        "round1Serials"?: string[];
        "round2Serials"?: string[];
        "status"?: string;
        "topic"?: string;
        "workspace_id"?: string | null;
        };
        Relationships: [];
      };
      "audit_log": {
        Row: {
        "action": string;
        "id": string;
        "newValue": string | null;
        "originalValue": string | null;
        "page": string;
        "reason": string;
        "timestamp": string;
        "userName": string;
        "userRole": string;
        };
        Insert: {
        "action": string;
        "id": string;
        "newValue"?: string | null;
        "originalValue"?: string | null;
        "page": string;
        "reason": string;
        "timestamp"?: string;
        "userName": string;
        "userRole": string;
        };
        Update: {
        "action"?: string;
        "id"?: string;
        "newValue"?: string | null;
        "originalValue"?: string | null;
        "page"?: string;
        "reason"?: string;
        "timestamp"?: string;
        "userName"?: string;
        "userRole"?: string;
        };
        Relationships: [];
      };
      "config": {
        Row: {
        "assessmentType": string;
        "examActivated": boolean;
        "examDurationMinutes": number;
        "examEndAt": string | null;
        "examStartAt": string | null;
        "id": string;
        "maxQuestions": number;
        "monitoring": Json;
        "protectionPassword": string;
        "randomizeOptions": boolean;
        "randomizeQuestions": boolean;
        "superadminPassword": string;
        };
        Insert: {
        "assessmentType"?: string;
        "examActivated"?: boolean;
        "examDurationMinutes"?: number;
        "examEndAt"?: string | null;
        "examStartAt"?: string | null;
        "id"?: string;
        "maxQuestions"?: number;
        "monitoring": Json;
        "protectionPassword"?: string;
        "randomizeOptions"?: boolean;
        "randomizeQuestions"?: boolean;
        "superadminPassword"?: string;
        };
        Update: {
        "assessmentType"?: string;
        "examActivated"?: boolean;
        "examDurationMinutes"?: number;
        "examEndAt"?: string | null;
        "examStartAt"?: string | null;
        "id"?: string;
        "maxQuestions"?: number;
        "monitoring"?: Json;
        "protectionPassword"?: string;
        "randomizeOptions"?: boolean;
        "randomizeQuestions"?: boolean;
        "superadminPassword"?: string;
        };
        Relationships: [];
      };
      "deletion_requests": {
        Row: {
        "createdAt": string;
        "id": string;
        "page": string;
        "reason": string;
        "requestedBy": string;
        "resolutionReason": string | null;
        "resolvedAt": string | null;
        "resolvedBy": string | null;
        "role": string;
        "scope": string;
        "status": string;
        };
        Insert: {
        "createdAt"?: string;
        "id": string;
        "page": string;
        "reason": string;
        "requestedBy": string;
        "resolutionReason"?: string | null;
        "resolvedAt"?: string | null;
        "resolvedBy"?: string | null;
        "role": string;
        "scope": string;
        "status"?: string;
        };
        Update: {
        "createdAt"?: string;
        "id"?: string;
        "page"?: string;
        "reason"?: string;
        "requestedBy"?: string;
        "resolutionReason"?: string | null;
        "resolvedAt"?: string | null;
        "resolvedBy"?: string | null;
        "role"?: string;
        "scope"?: string;
        "status"?: string;
        };
        Relationships: [];
      };
      "exam_eligibility": {
        Row: {
        "email": string;
        "id": string;
        "overrideBy": string | null;
        "overrideReason": string | null;
        "reason": string;
        "sessionId": string;
        "status": string;
        "updatedAt": string;
        "workspace_id": string | null;
        };
        Insert: {
        "email": string;
        "id": string;
        "overrideBy"?: string | null;
        "overrideReason"?: string | null;
        "reason": string;
        "sessionId": string;
        "status": string;
        "updatedAt"?: string;
        "workspace_id"?: string | null;
        };
        Update: {
        "email"?: string;
        "id"?: string;
        "overrideBy"?: string | null;
        "overrideReason"?: string | null;
        "reason"?: string;
        "sessionId"?: string;
        "status"?: string;
        "updatedAt"?: string;
        "workspace_id"?: string | null;
        };
        Relationships: [];
      };
      "questions": {
        Row: {
        "answer": string;
        "createdAt": string;
        "difficulty": string | null;
        "id": string;
        "options": string[] | null;
        "subject": string | null;
        "text": string;
        "type": string;
        "workspace_id": string | null;
        };
        Insert: {
        "answer": string;
        "createdAt"?: string;
        "difficulty"?: string | null;
        "id": string;
        "options"?: string[] | null;
        "subject"?: string | null;
        "text": string;
        "type": string;
        "workspace_id"?: string | null;
        };
        Update: {
        "answer"?: string;
        "createdAt"?: string;
        "difficulty"?: string | null;
        "id"?: string;
        "options"?: string[] | null;
        "subject"?: string | null;
        "text"?: string;
        "type"?: string;
        "workspace_id"?: string | null;
        };
        Relationships: [];
      };
      "results": {
        Row: {
        "answers": Json;
        "attemptId": string;
        "class": string;
        "classSN": string;
        "email": string;
        "examSessionId": string;
        "id": string;
        "name": string;
        "percentage": number;
        "score": number;
        "submittedAt": string;
        "totalQuestions": number;
        "workspace_id": string | null;
        };
        Insert: {
        "answers": Json;
        "attemptId": string;
        "class": string;
        "classSN": string;
        "email": string;
        "examSessionId": string;
        "id": string;
        "name": string;
        "percentage": number;
        "score": number;
        "submittedAt"?: string;
        "totalQuestions": number;
        "workspace_id"?: string | null;
        };
        Update: {
        "answers"?: Json;
        "attemptId"?: string;
        "class"?: string;
        "classSN"?: string;
        "email"?: string;
        "examSessionId"?: string;
        "id"?: string;
        "name"?: string;
        "percentage"?: number;
        "score"?: number;
        "submittedAt"?: string;
        "totalQuestions"?: number;
        "workspace_id"?: string | null;
        };
        Relationships: [];
      };
      "students": {
        Row: {
        "class": string;
        "classSN": string;
        "createdAt": string;
        "email": string;
        "gender": string | null;
        "id": string;
        "name": string;
        "phone": string | null;
        "updatedAt": string | null;
        "workspace_id": string | null;
        };
        Insert: {
        "class": string;
        "classSN": string;
        "createdAt"?: string;
        "email": string;
        "gender"?: string | null;
        "id": string;
        "name": string;
        "phone"?: string | null;
        "updatedAt"?: string | null;
        "workspace_id"?: string | null;
        };
        Update: {
        "class"?: string;
        "classSN"?: string;
        "createdAt"?: string;
        "email"?: string;
        "gender"?: string | null;
        "id"?: string;
        "name"?: string;
        "phone"?: string | null;
        "updatedAt"?: string | null;
        "workspace_id"?: string | null;
        };
        Relationships: [];
      };
      "user_roles": {
        Row: {
        "created_at": string;
        "id": string;
        "role": string;
        "user_id": string;
        };
        Insert: {
        "created_at"?: string;
        "id"?: string;
        "role": string;
        "user_id": string;
        };
        Update: {
        "created_at"?: string;
        "id"?: string;
        "role"?: string;
        "user_id"?: string;
        };
        Relationships: [];
      };
      "workspaces": {
        Row: {
        "created_at": string;
        "id": string;
        "name": string;
        "tutor_id": string;
        };
        Insert: {
        "created_at"?: string;
        "id"?: string;
        "name": string;
        "tutor_id": string;
        };
        Update: {
        "created_at"?: string;
        "id"?: string;
        "name"?: string;
        "tutor_id"?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      "auto_submit_expired_exams": {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      "current_workspace_id": {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      "get_exam_config": {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      "has_role": {
        Args: {
        "_role": string;
        "_user_id": string;
        };
        Returns: Json;
      };
      "student_cbt_log": {
        Args: {
        "p_action": string;
        "p_email": string;
        "p_new_value": string;
        "p_page": string;
        "p_reason": string;
        };
        Returns: Json;
      };
      "student_cbt_result": {
        Args: {
        "p_class_sn": string;
        "p_email": string;
        };
        Returns: Json;
      };
      "student_cbt_start": {
        Args: {
        "p_class_sn": string;
        "p_email": string;
        };
        Returns: Json;
      };
      "student_cbt_submit": {
        Args: {
        "p_answers": Json;
        "p_attempt_id": string;
        "p_class_sn": string;
        "p_email": string;
        "p_session_id": string;
        };
        Returns: Json;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type ExternalTables<T extends keyof ExternalDatabase['public']['Tables']> =
  ExternalDatabase['public']['Tables'][T]['Row'];
